stages:
  prepare:
    cmd: python src/data/split_data.py
    deps:
      - data/raw_data/raw.csv
      - src/data/split_data.py
      - params.yaml
    outs:
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
      - data/processed_data/y_train.csv
      - data/processed_data/y_test.csv

  normalize:
    cmd: python src/data/normalize_data.py
    deps:
      - src/data/normalize_data.py
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
    outs:
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/X_test_scaled.csv

  grid_search:
    cmd: python src/models/grid_search.py
    deps:
      - src/models/grid_search.py
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
      - params.yaml
    params:
      - hyperparameters.n_estimators
      - hyperparameters.max_depth
      - hyperparameters.min_samples_split
    outs:
      - models/best_params.pkl

  train:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
      - models/best_params.pkl
    params:
      - hyperparameters.n_estimators
      - hyperparameters.max_depth
      - hyperparameters.min_samples_split
    outs:
      - models/trained_model.pkl

  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
      - src/models/evaluate_model.py
      - data/processed_data/X_test_scaled.csv
      - data/processed_data/y_test.csv
      - models/trained_model.pkl
    outs:
      - data/processed_data/predictions.csv 
    metrics:
      - metrics/scores.json:
          cache: false

